data_calibration_node:
  ros__parameters:
    polynomial_order: 2  # 다항식 차수 (현재는 2차)

    # 센서 0의 캘리브레이션 계수
    sensor0:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 1의 캘리브레이션 계수
    sensor1:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 2의 캘리브레이션 계수
    sensor2:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 3의 캘리브레이션 계수
    sensor3:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0


    # 센서 4의 캘리브레이션 계수
    sensor4:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 5의 캘리브레이션 계수
    sensor5:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 6의 캘리브레이션 계수
    sensor6:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 7의 캘리브레이션 계수
    sensor7:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 8의 캘리브레이션 계수
    sensor8:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

      # 센서 9의 캘리브레이션 계수
    sensor9:
      a: 203.65
      b: -1186.69
      c: 1413.60
      d: 0.0
      e: 0.0
      f: 0.0

    # 각 센서별 파라미터 설정 필요
