USART_actuator_node:
  ros__parameters:
    actuator_port: /dev/ttyACM0
    actuator_baudrate: 115200

USART_displacement_node:
  ros__parameters:
    displacement_port: /dev/ttyUSB0
    displacement_baudrate: 1000000
    displacement_gain: 0.000062
